#!/bin/bash
find .. -name "*flymake*" -exec rm -f {} \;
parallel ./cleanfile ::: ../hkl.h ../hkl/*.[ch] ../tests/*.[ch] ../tests/tap/*.[ch] ../gui/*.[ch] ../binoculars-ng/binoculars/*.[ch]
parallel ./indent ::: ../hkl.h ../hkl/*.[ch] ../tests/*.[ch] ../tests/tap/*.[ch] ../gui/*.[ch] ../binoculars-ng/binoculars/*.[ch]
parallel ./indent-c++ ::: ../hkl3d/*.cpp ../hkl3d/*.h
parallel ./indent-python ::: ../tests/bindings/*.py
find .. -name "*flymake*" -exec rm -f {} \;
